name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ArtemSBulgakov/buildozer-action@v1
    - uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: ./bin/*.apk
